"use client";
import Papa from "papaparse";
import { useEffect, useMemo, useRef, useState } from "react";
import { Download, FileUp, Moon, RefreshCcw, Sparkles, Sun, Upload, X } from "lucide-react";
import { Toaster, toast } from "sonner";
import type { ImportResponse } from "@groweasy/shared";

type Preview = { columns: string[]; rows: Record<string, string>[] };
const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000";
const download = (name: string, data: string, type = "text/csv") => { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([data], { type })); link.download = name; link.click(); URL.revokeObjectURL(link.href); };
const toCsv = (rows: Record<string, unknown>[]) => { if (!rows.length) return ""; const columns = Object.keys(rows[0]); return [columns, ...rows.map((r) => columns.map((key) => `"${String(r[key] ?? "").replaceAll('"', '""')}"`))].map((r) => r.join(",")).join("\n"); };

export default function Home() {
  const input = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<Preview | null>(null); const [result, setResult] = useState<ImportResponse | null>(null); const [busy, setBusy] = useState(false); const [tab, setTab] = useState<"records" | "skipped" | "warnings">("records"); const [dark, setDark] = useState(true);
  useEffect(() => setDark(localStorage.getItem("groweasy-theme") !== "light"), []);
  const toggleTheme = () => setDark((current) => { const next = !current; localStorage.setItem("groweasy-theme", next ? "dark" : "light"); return next; });
  const stage = busy ? "Processing AI batches and validating CRM records…" : result ? "Import complete" : preview ? "Review your file before AI processing" : "Upload any lead CSV — GrowEasy maps the messy columns for you.";
  const choose = (candidate?: File) => { if (!candidate) return; if (!candidate.name.toLowerCase().endsWith(".csv") || candidate.size > 5 * 1024 * 1024) return toast.error("Choose a CSV file smaller than 5MB."); setFile(candidate); Papa.parse<Record<string, string>>(candidate, { header: true, skipEmptyLines: "greedy", complete: ({ data, meta, errors }) => { if (errors.length) return toast.error(errors[0].message); setPreview({ columns: meta.fields ?? [], rows: data }); setResult(null); } }); };
  const process = async () => { if (!file) return; setBusy(true); try { const form = new FormData(); form.append("file", file); const response = await fetch(`${API}/api/import`, { method: "POST", body: form }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Import failed"); setResult(body); setTab("records"); toast.success("AI import finished"); } catch (error) { const message = error instanceof TypeError && error.message === "Failed to fetch" ? `Cannot reach the API at ${API}. Start the API with corepack pnpm --filter @groweasy/api dev.` : error instanceof Error ? error.message : "Import failed"; toast.error(message); } finally { setBusy(false); } };
  const currentRows = useMemo(() => preview?.rows.slice(0, 100) ?? [], [preview]);
  return <main className={`min-h-screen p-4 md:p-10 ${dark ? "dark" : ""}`}><Toaster richColors position="top-right" /><div className="mx-auto max-w-7xl"><header className="mb-8 flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-brand text-xl font-black text-white">G</div><div><p className="text-lg font-bold">GrowEasy</p><p className="text-sm text-slate-500">CRM workspace</p></div></div><button onClick={toggleTheme} className="rounded-xl border border-slate-200 bg-white p-3" aria-label={dark ? "Switch to light mode" : "Switch to dark mode"} aria-pressed={dark}>{dark ? <Sun size={18}/> : <Moon size={18}/>}</button></header><section className="glass overflow-hidden rounded-[28px] border border-white shadow-float"><div className="border-b border-slate-100 px-6 py-5 md:px-8"><div className="flex items-start justify-between gap-4"><div><p className="mb-1 flex items-center gap-2 text-sm font-semibold text-brand"><Sparkles size={16}/> AI-assisted import</p><h1 className="text-2xl font-bold tracking-tight">Import Leads via CSV</h1><p className="mt-1 text-sm text-slate-500">{stage}</p></div>{file && !busy && <button onClick={() => { setFile(null); setPreview(null); setResult(null); }} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X size={20}/></button>}</div></div>{!preview ? <UploadState input={input} choose={choose}/> : result ? <Results result={result} tab={tab} setTab={setTab} restart={() => { setFile(null); setPreview(null); setResult(null); }} /> : <PreviewState file={file!} preview={preview} rows={currentRows} busy={busy} process={process}/>}</section></div></main>;
}
function UploadState({ input, choose }: { input: React.RefObject<HTMLInputElement | null>; choose: (file?: File) => void }) { return <div className="p-6 md:p-8"><div onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); choose(e.dataTransfer.files[0]); }} className="grid min-h-72 place-items-center rounded-2xl border-2 border-dashed border-emerald-200 bg-mint/40 p-8 text-center"><div><div className="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-white text-brand shadow"><Upload/></div><h2 className="font-semibold">Drag and drop your CSV here</h2><p className="mt-2 text-sm text-slate-500">Supports .csv files up to 5MB</p><button onClick={() => input.current?.click()} className="mt-5 rounded-xl bg-brand px-5 py-3 text-sm font-semibold text-white">Choose CSV file</button><input ref={input} onChange={(e) => choose(e.target.files?.[0])} type="file" accept=".csv,text/csv" hidden/></div></div><div className="mt-5 flex flex-col items-start justify-between gap-4 rounded-xl bg-slate-50 p-4 md:flex-row md:items-center"><p className="max-w-3xl text-sm text-slate-600">Required fields are not fixed. Upload any valid lead CSV — AI will map messy columns into GrowEasy CRM fields after you confirm.</p><a href="/sample.csv" download className="flex shrink-0 items-center gap-2 text-sm font-semibold text-brand"><Download size={16}/> Download sample template</a></div></div> }
function PreviewState({ file, preview, rows, busy, process }: { file: File; preview: Preview; rows: Record<string,string>[]; busy: boolean; process: () => void }) { return <div className="p-6 md:p-8"><div className="mb-6 grid gap-3 md:grid-cols-3"><Metric label="File" value={file.name}/><Metric label="Data rows" value={String(preview.rows.length)}/><Metric label="Detected columns" value={String(preview.columns.length)}/></div><div className="scrollbar max-h-[430px] overflow-auto rounded-xl border border-slate-200"><table className="min-w-full text-left text-sm"><thead className="sticky top-0 bg-slate-900 text-white"><tr>{preview.columns.map((column) => <th key={column} className="whitespace-nowrap px-4 py-3 font-medium">{column}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index} className="border-t border-slate-100 bg-white">{preview.columns.map((column) => <td key={column} className="max-w-56 truncate px-4 py-3 text-slate-600">{row[column]}</td>)}</tr>)}</tbody></table></div><footer className="mt-6 flex items-center justify-between"><p className="text-sm text-slate-500">Previewing first {Math.min(rows.length, 100)} rows locally. Nothing has been uploaded yet.</p><button disabled={busy} onClick={process} className="flex items-center gap-2 rounded-xl bg-brand px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{busy ? <><RefreshCcw className="animate-spin" size={17}/> Processing with AI</> : <><Sparkles size={17}/> Confirm & Process with AI</>}</button></footer></div> }
function Results({ result, tab, setTab, restart }: { result: ImportResponse; tab: "records" | "skipped" | "warnings"; setTab: (x: "records" | "skipped" | "warnings") => void; restart: () => void }) { const rows = tab === "records" ? result.records : tab === "skipped" ? result.skippedRecords : result.warnings.map((warning) => ({ warning })); return <div className="p-6 md:p-8"><div className="mb-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Rows uploaded" value={String(result.summary.totalRows)}/><Metric label="Imported" value={String(result.summary.imported)} green/><Metric label="Skipped" value={String(result.summary.skipped)}/><Metric label="AI batches" value={String(result.summary.batchesProcessed)}/></div><div className="mb-4 flex flex-wrap gap-2">{(["records", "skipped", "warnings"] as const).map((item) => <button key={item} onClick={() => setTab(item)} className={`rounded-lg px-4 py-2 text-sm font-semibold ${tab === item ? "bg-brand text-white" : "bg-slate-100 text-slate-600"}`}>{item === "records" ? "Imported Records" : item === "skipped" ? `Skipped Records (${result.skippedRecords.length})` : `Warnings (${result.warnings.length})`}</button>)}</div><div className="scrollbar max-h-[430px] overflow-auto rounded-xl border border-slate-200"><table className="min-w-full text-left text-sm"><thead className="sticky top-0 bg-slate-900 text-white"><tr>{Object.keys(rows[0] ?? { result: "No records" }).map((key) => <th key={key} className="whitespace-nowrap px-4 py-3 font-medium">{key}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr className="border-t border-slate-100 bg-white" key={index}>{Object.entries(row).map(([key, value]) => <td key={key} className="max-w-72 px-4 py-3 align-top text-slate-600">{typeof value === "object" ? JSON.stringify(value) : String(value)}</td>)}</tr>)}</tbody></table></div><footer className="mt-6 flex flex-wrap justify-end gap-3"><button onClick={() => download("groweasy-crm-records.csv", toCsv(result.records))} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold">Download CRM CSV</button><button onClick={() => download("groweasy-import.json", JSON.stringify(result, null, 2), "application/json")} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold">Download JSON</button><button onClick={() => download("groweasy-skipped.csv", toCsv(result.skippedRecords as unknown as Record<string, unknown>[]))} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold">Download Skipped Rows</button><button onClick={restart} className="flex items-center gap-2 rounded-xl bg-brand px-4 py-2 text-sm font-semibold text-white"><FileUp size={16}/> Start New Import</button></footer></div> }
function Metric({ label, value, green }: { label: string; value: string; green?: boolean }) { return <div className="rounded-xl border border-slate-100 bg-white p-4"><p className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</p><p className={`mt-2 truncate text-xl font-bold ${green ? "text-brand" : ""}`}>{value}</p></div> }
